### ISSUE TITLE
Your profile is a nice start | just a small suggestion

### ISSUE THREAD

**Issue by ayan-biswas0412** [SouvikChoudhury360/SouvikChoudhury360#1]
Hi I am Ayan , 2nd year UG in ETCE depth, JU, saw your profile in but Github Feed , your profile is a nice start for Github
You can align all the badges in single line rather than by putting them one after another , it will look more beautiful

<img width="749" alt="image" src="https://user-images.githubusercontent.com/52851184/118859657-1b0a6b80-b8f8-11eb-809f-abbf984488fa.png">

**Comment by SouvikChoudhury360** [comment]
Yes sir, I will surely do the same.
Thank you.

**Comment by ayan-biswas0412** [comment]
> Yes sir, I will surely do the same.
> Thank you.

are bhai I am not sir 😅

**Comment by SouvikChoudhury360** [comment]
thank you dada 😅
